/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jOttvqBBw9k
 */
import { Avatar } from "app/components/ui/avatar";
import { Badge } from "app/components/ui/badge";
import { CardContent, Card } from "app/components/ui/card";

export function CardStudent() {
  return (
    <div className="bg-gray-1000 py-6 sm:py-12 ">
      <div className="container px-4">
        <Card className="backdrop-blur-sm bg-opacity-90 bg-gray-1000 p-0">
          <CardContent className="p-0 text-white">
            <div className="grid md:grid-cols-3 items-center gap-4 p-6">
              <div className="flex flex-col items-center space-y-2 md:col-span-1 md:items-start">
                <Avatar className="w-24 h-24 border-4 border-gray-900" />
                <div className="text-center md:text-left">
                  <h1 className="text-3xl font-bold">Alice Johnson</h1>
                  <p className="text-sm text-gray-100">@alicej</p>
                </div>
              </div>
              <div className="space-y-4 md:col-span-2">
                <div className="space-y-2">
                  <div className="flex items-center space-x-2">
                    <h2 className="text-2xl font-bold">UX Designer</h2>
                    <Badge>Pro</Badge>
                  </div>
                  <p className="text-sm text-gray-500">
                    Passionate about creating beautiful and intuitive user
                    experiences. Currently exploring the intersection of AR and
                    design.
                  </p>
                </div>
                <div className="grid gap-2">
                  <div className="flex items-center space-x-2">
                    <WorkflowIcon className="w-4 h-4 text-gray-500" />
                    <div className="space-y-0.5">
                      <p className="text-sm font-semibold">Experience</p>
                      <p className="text-xs text-gray-500">
                        UX Designer at Acme Inc
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <GraduationCapIcon className="w-4 h-4 text-gray-500" />
                    <div className="space-y-0.5">
                      <p className="text-sm font-semibold">Education</p>
                      <p className="text-xs text-gray-500">
                        BSc in Design at State University
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    <LocateIcon className="w-4 h-4 text-gray-500" />
                    <div className="space-y-0.5">
                      <p className="text-sm font-semibold">Location</p>
                      <p className="text-xs text-gray-500">San Francisco, CA</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function WorkflowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="3" y="3" rx="2" />
      <path d="M7 11v4a2 2 0 0 0 2 2h4" />
      <rect width="8" height="8" x="13" y="13" rx="2" />
    </svg>
  );
}

function GraduationCapIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 10v6M2 10l10-5 10 5-10 5z" />
      <path d="M6 12v5c3 3 9 3 12 0v-5" />
    </svg>
  );
}

function LocateIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  );
}
