/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o4fUJkY88AV
 */
import Link from "next/link"
import { CardContent, Card } from "app/components/ui/card"

export function TestCards() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Portfolio
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Welcome to the Gallery</h1>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Discover the world through my eyes. Each piece tells a different story.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 lg:grid-cols-3 lg:gap-12">
              <Card className="w-full max-w-none">
                <div className="aspect-gallery overflow-hidden rounded-xl">
                  <img
                    alt="Artwork"
                    className="aspect-[16/9] object-cover object-center"
                    height="300"
                    src="/placeholder.svg"
                    width="500"
                  />
                </div>
                <CardContent className="p-4 space-y-4">
                  <div className="space-y-2">
                    <h3 className="text-xl font-bold">Sunset on the Horizon</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      The beauty of nature captured in a single frame.
                    </p>
                  </div>
                </CardContent>
              </Card>
              <Card className="w-full max-w-none">
                <div className="aspect-gallery overflow-hidden rounded-xl">
                  <img
                    alt="Artwork"
                    className="aspect-[16/9] object-cover object-center"
                    height="300"
                    src="/placeholder.svg"
                    width="500"
                  />
                </div>
                <CardContent className="p-4 space-y-4">
                  <div className="space-y-2">
                    <h3 className="text-xl font-bold">City of Dreams</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      Urban landscapes that inspire imagination.
                    </p>
                  </div>
                </CardContent>
              </Card>
              <Card className="w-full max-w-none">
                <div className="aspect-gallery overflow-hidden rounded-xl">
                  <img
                    alt="Artwork"
                    className="aspect-[16/9] object-cover object-center"
                    height="300"
                    src="/placeholder.svg"
                    width="500"
                  />
                </div>
                <CardContent className="p-4 space-y-4">
                  <div className="space-y-2">
                    <h3 className="text-xl font-bold">Serenity in Blue</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Calm waters and peaceful reflections.</p>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
