import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
// import Navbar from "app/components/Navbar";
import Providers from "./Providers";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-[#141414] min-h-screen ${montserrat.className}`}>
        <Providers>
          {/* <Navbar /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
